import type { Metadata } from "next";
import React from 'react';
import { AntdRegistry } from '@ant-design/nextjs-registry';
import "@/app/ui/globals.css"

export const metadata: Metadata = {
  title: "POC",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: React.PropsWithChildren) {
  return (
    <html lang="en">
      <body>
        <AntdRegistry>{children}</AntdRegistry>
      </body>
    </html>
  );
}
